language: node_js
node_js:
  - 8

before_install:
  # Install Nix
  - curl https://nixos.org/nix/install | sh

script:
  # Do linting, coverage, and build docs (to upload to Github pages)
  - make lint
  - make cover
  - make docs

  # Generate Nix files
  # node2nix produces a lot of output on stderr which causes Travis to say
  # "The job exceeded the maximum log length, and has been terminated."
  # There does not appear to be an option to turn this off so redirect it to file.
  # Travis will also kill a build if no output is received for 10 mins, so
  # use `travis_wait` to ensure that does not happen.
  - (cd nix/pkgs/development/node-packages; travis_wait 60 ./generate.sh)
  - (cd nix/pkgs/development/python-modules; ./generate.sh)
  - (cd nix/pkgs/development/r-modules; ./generate.sh)

# Upload test coverage to codecov
# See https://docs.codecov.io/v5.0.0/docs/about-the-codecov-bash-uploader
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Prevent Github Pages from using Jekyll
# which causes docs files starting with underscores to be ignored
before_deploy:
  - touch docs/.nojekyll

deploy:
  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
