language: nix
nix: 2.1.3

script:
  # node2nix produces a lot of output on stderr which causes Travis to say
  # "The job exceeded the maximum log length, and has been terminated."
  # There does not appear to be an option to turn this off so redirect it to file.
  # Travis will also kill a build if no output is received for 10 mins, so
  # use `travis_wait` to ensure that does not happen.
  - (cd nix/pkgs/development/node-packages; travis_wait 60 ./generate.sh)
  - (cd nix/pkgs/development/python-modules; ./generate.sh)
  - (cd nix/pkgs/development/r-modules; ./generate.sh)
