language: nix
nix: 2.1.3
script:
# - "(cd pkgs/development/node-packages; travis_wait 60 ./generate.sh)"
# - "(cd pkgs/development/python-modules; ./generate.sh)"
# - "(cd pkgs/development/r-modules; ./generate.sh)"
- ./deploy.sh
branches:
  only:
  - test-travis
before_install:
- nix-env -i bash openssl
- mkdir -p $HOME/.ssh
- openssl aes-256-cbc -K $encrypted_a792dbab8fa9_key -iv $encrypted_a792dbab8fa9_iv
  -in travis.enc -out $HOME/.ssh/id_rsa -d
- chmod 600 $HOME/.ssh/id_rsa
