language: node_js
node_js:
  - "10"

cache:
  directories:
    - /nix

before_install:
  # Install Nix
  - curl https://nixos.org/nix/install | sh
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh

# Do linting, coverage, and build docs (to upload to Github pages)
script:
  - make lint
  # Do an update to populate db prior to testing
  - npx ts-node src/cli.ts update nixos-18.09
  - make cover
  - make docs
  # Dump the packages to a TSV file for browsing (until we have a better way of browsing them)
  - npx ts-node src/cli.ts dump packages --tsv > docs/packages.tsv

  # Generate Nix files
  # node2nix produce a lot of output on stderr which causes Travis to say
  # "The job exceeded the maximum log length, and has been terminated."
  # There does not appear to be a node2nix option to turn this off.
  # Travis will also kill a build if no output is received for 10 mins, so
  # use `travis_wait` to ensure that does not happen.
  #- (cd nix/pkgs/development/node-packages; travis_wait 60 ./generate.sh)
  #- (cd nix/pkgs/development/python-modules; ./generate.sh)
  #- (cd nix/pkgs/development/r-modules; ./generate.sh)

# Upload test coverage to codecov
# See https://docs.codecov.io/v5.0.0/docs/about-the-codecov-bash-uploader
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Prevent Github Pages from using Jekyll
# which causes docs files starting with underscores to be ignored
before_deploy:
  - touch docs/.nojekyll

deploy:
  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
