apiVersion: v1
kind: PersistentVolume
metadata:
  name: nixster-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  # Minikube will persist files stored under /data so we use that to simulate
  # a persistent disk in production
  # See https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md
  hostPath:
    path: /data/nixroot


# The following PVCs have different accessModes for testing what was needed
# for build and serve phases. In production, only one should be needed?

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixster-pvc-rwm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixster-pvc-rwo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixster-pvc-rom
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
