# An example Kubernetes deployment for building Nixta environments
# Designed for testing using Minikube but should
# require little modification for use in a production cluster.

apiVersion: batch/v1
kind: Job
metadata:
  name: nixta-build-job
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      initContainers:
        # Create the `profiles` directory
        # This is a workaround which could be avoided by a fix in the `nixta` app
        - name: init-nix-volume
          image: busybox
          command: ["sh", "-c", "mkdir -p /nixroot/nix/profiles/"]
          volumeMounts:
            - name: nix-volume
              mountPath: /nixroot
      containers:
        # Build container with write access to the `/nixroot` directory
        - name: build-container
          image: stencila/nixta
          # Don't pull image, instead use the one built locally
          imagePullPolicy: Never
          # Build the environment into the `/nixroot` directory
          # To keep thing fast and small only build a small image
          command: ["nixta"]
          args: ["build", "r", "--store", "/nixroot"]
          volumeMounts:
            - name: nix-volume
              mountPath: /nixroot
          # Build needs to be priviledged
          securityContext:
            privileged: true
      # Use the ReadWriteOnce PVC
      volumes:
        - name: nix-volume
          persistentVolumeClaim:
            claimName: nixta-pvc-rwo
